---
plugin: gcp_compute
zones:
- us-central1-a
- us-central1-b
- us-central1-c
- us-central1-f
projects:
- terraform-on-gcp-414809
hostnames:
- test
auth_kind: serviceaccount
compose:
ansible_host: networkInterfaces[0].networkIP